<?php
ini_set('display_errors', 1);
error_reporting(E_ALL);

// Duomenų bazės prisijungimas
$servername = "localhost";
$username = "itech024";
$password = "A6D*dFcf2VtZ";
$dbname = "itech024";

$conn = new mysqli($servername, $username, $password, $dbname);
$conn->set_charset("utf8mb4");

// Ryšio tikrinimas
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// receptu masyvas
$recipes = [
    [
        "title" => "Sultingas kepsnys",
        "desc" => "Jautienos kepsnys su žolelėmis.",
        "portions" => 2,
        "time" => "30 min.",
        "author" => "Greta",
        "date" => "2025-04-11",
        "likes" => 26,
        "comments" => 3,
        "tips" => "Neperkepk – vidus turi likti šiek tiek rausvas.",
        "ingredients" => ["Jautiena (2 kepsniai)", "Druska", "Pipirai", "Rozmarinas", "Alyvuogių aliejus"],
        "instructions" => [
            "Įkaitink grilį arba keptuvę.",
            "Pagardink kepsnius druska, pipirais ir rozmarinu.",
            "Apkepk po 3–4 min. iš kiekvienos pusės.",
            "Leisk pailsėti 5 minutes prieš patiekdami."
        ],
        "img" => "images/kepsnys.jpg",
        "photos" => ["images/kepsnys.jpg", "images/kepsnys1.webp", "images/kepsnys2.webp"],
        "meal" => "Vakarienė",
        "type" => "Pagrindiniai patiekalai",
        "diet" => "Sveika mityba",
        "cuisine" => "Lietuvių"
    ],
    [
        "title" => "Makaronai su vištiena",
        "desc" => "Greiti ir sotūs pietūs su saulėje džiovintais pomidorais.",
        "portions" => 2,
        "time" => "25 min.",
        "author" => "Lina",
        "date" => "2025-04-10",
        "likes" => 14,
        "comments" => 2,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/makaronai.jpg",
        "photos" => ["images/makaronai.jpg"],
        "meal" => "Pietūs",
        "type" => "Pagrindiniai patiekalai",
        "diet" => "Pietūs",
        "cuisine" => "Italų"
    ],
    [
        "title" => "Moliūgų sriuba",
        "desc" => "Kreminė trinta moliūgų sriuba su kokosų pienu.",
        "portions" => 4,
        "time" => "20 min.",
        "author" => "Jonas",
        "date" => "2025-04-09",
        "likes" => 19,
        "comments" => 1,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/sriubaa.jpg",
        "photos" => ["images/sriubaa.jpg"],
        "meal" => "Pietūs",
        "type" => "Sriubos",
        "diet" => "Sveika mityba",
        "cuisine" => "Lietuvių"
    ],
    [
        "title" => "Avokado skrebutis",
        "desc" => "Avokadų skrebutis su įvairiais pagardais – paprasta ir skanu.",
        "portions" => 1,
        "time" => "10 min.",
        "author" => "Eglė",
        "date" => "2025-04-08",
        "likes" => 30,
        "comments" => 4,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/avokadas.jpg",
        "photos" => ["images/avokadas.jpg"],
        "meal" => "Pusryčiai",
        "type" => "Pusryčiai",
        "diet" => "Veganiški patiekalai",
        "cuisine" => "Lietuvių"
    ],
    [
        "title" => "Cinamoninės bandelės",
        "desc" => "Minkštos bandelės - Skanus desertas prie kavos.",
        "portions" => 6,
        "time" => "45 min.",
        "author" => "Toma",
        "date" => "2025-04-07",
        "likes" => 41,
        "comments" => 6,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/bandeless.jpg",
        "photos" => ["images/bandeless.jpg"],
        "meal" => "Desertai",
        "type" => "Desertai",
        "diet" => "Vaikams",
        "cuisine" => "Lietuvių"
    ],
    [
        "title" => "Avižinė košė",
        "desc" => "Sveiki pusryčiai su uogomis.",
        "portions" => 1,
        "time" => "12 min.",
        "author" => "Milda",
        "date" => "2025-04-06",
        "likes" => 11,
        "comments" => 0,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/kosee.jpg",
        "photos" => ["images/kosee.jpg"],
        "meal" => "Pusryčiai",
        "type" => "Pusryčiai",
        "diet" => "Sveika mityba",
        "cuisine" => "Lietuvių"
    ],
    [
        "title" => "Bulvių apkepas",
        "desc" => "Kreminis bulvių apkepas su česnaku, grietinėle ir traškia sūrio plutele .",
        "portions" => 4,
        "time" => "35 min.",
        "author" => "Dainius",
        "date" => "2025-04-05",
        "likes" => 21,
        "comments" => 1,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/pietus.jpg",
        "photos" => ["images/pietus.jpg"],
        "meal" => "Pietūs",
        "type" => "Pagrindiniai patiekalai",
        "diet" => "Be glitimo",
        "cuisine" => "Lietuvių"
    ],
    [
        "title" => "Veganiški makaronai",
        "desc" => "Daržovėmis pagardinti makaronai su alyvuogėmis ir artišokais.",
        "portions" => 2,
        "time" => "30 min.",
        "author" => "Monika",
        "date" => "2025-04-04",
        "likes" => 17,
        "comments" => 2,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/makaronai_veganiskai.jpg",
        "photos" => ["images/makaronai_veganiskai.jpg"],
        "meal" => "Pietūs",
        "type" => "Pagrindiniai patiekalai",
        "diet" => "Veganiški patiekalai",
        "cuisine" => "Italų"
    ],
    [
        "title" => "Aguonų pienas",
        "desc" => "Tradicinis šventinis gėrimas su aguonomis ir medumi.",
        "portions" => 6,
        "time" => "15 min.",
        "author" => "Aistė",
        "date" => "2025-04-03",
        "likes" => 10,
        "comments" => 0,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/aguonpienis.jpg",
        "photos" => ["images/aguonpienis.jpg"],
        "meal" => "Gėrimai",
        "type" => "Gėrimai",
        "diet" => "Veganiški patiekalai",
        "cuisine" => "Lietuvių"
    ],
    [
        "title" => "Saldžiarūgščiai avinžirniai",
        "desc" => "Avinžirnių troškinys su saldžiarūgščiu padažu ir ryžiais.",
        "portions" => 4,
        "time" => "40 min.",
        "author" => "Tadas",
        "date" => "2025-04-02",
        "likes" => 8,
        "comments" => 1,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/avinzirniai.jpg",
        "photos" => ["images/avinzirniai.jpg"],
        "meal" => "Pietūs",
        "type" => "Pagrindiniai patiekalai",
        "diet" => "Veganiški patiekalai",
        "cuisine" => "Japonų"
    ],
    [
        "title" => "Cezario salotos",
        "desc" => "Klasikinės salotos su parmezanu ir traškiais skrebučiais.",
        "portions" => 2,
        "time" => "15 min.",
        "author" => "Karolina",
        "date" => "2025-04-01",
        "likes" => 25,
        "comments" => 3,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/cesario_salotos.jpg",
        "photos" => ["images/cesario_salotos.jpg"],
        "meal" => "Pietūs",
        "type" => "Salotos",
        "diet" => "Sveika mityba",
        "cuisine" => "Italų"
    ],
    [
        "title" => "Gaivios daržovių salotos",
        "desc" => "Agurkų, pomidorų ir svogūnų salotos su grietinės užpilu.",
        "portions" => 2,
        "time" => "10 min.",
        "author" => "Justina",
        "date" => "2025-03-31",
        "likes" => 13,
        "comments" => 1,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/gaivios_salotos.jpg",
        "photos" => ["images/gaivios_salotos.jpg"],
        "meal" => "Salotos",
        "type" => "Salotos",
        "diet" => "Vegetariški patiekalai",
        "cuisine" => "Lietuvių"
    ],
    [
        "title" => "Kepta duona su sūrio padažu",
        "desc" => "Traški kepta duona su česnakiniu sūrio padažu.",
        "portions" => 5,
        "time" => "15 min.",
        "author" => "Martynas",
        "date" => "2025-03-30",
        "likes" => 28,
        "comments" => 2,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/kepta duona.jpg",
        "photos" => ["images/kepta duona.jpg"],
        "meal" => "Užkandžiai",
        "type" => "Užkandžiai",
        "diet" => "Be glitimo",
        "cuisine" => "Lietuvių"
    ],
    [
        "title" => "Spanguolių kisielius",
        "desc" => "Tradicinis šventinis saldus gėrimas iš spanguolių.",
        "portions" => 8,
        "time" => "20 min.",
        "author" => "Gabija",
        "date" => "2025-03-29",
        "likes" => 9,
        "comments" => 0,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/kisielius.jpg",
        "photos" => ["images/kisielius.jpg"],
        "meal" => "Gėrimai",
        "type" => "Gėrimai",
        "diet" => "Vaikams",
        "cuisine" => "Lietuvių"
    ],
    [
        "title" => "Klasikinė lazanija",
        "desc" => "Sotus ir greitas patiekalas su bolonese padažu.",
        "portions" => 4,
        "time" => "40 min.",
        "author" => "Laurynas",
        "date" => "2025-03-28",
        "likes" => 22,
        "comments" => 3,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/lazanija.jpg",
        "photos" => ["images/lazanija.jpg"],
        "meal" => "Vakarienė",
        "type" => "Pagrindiniai patiekalai",
        "diet" => "Vaikams",
        "cuisine" => "Italų"
    ],
    [
        "title" => "Gaivus limonadas",
        "desc" => "Citrinų gėrimas su mėtų lapeliais karštai dienai.",
        "portions" => 6,
        "time" => "10 min.",
        "author" => "Rūta",
        "date" => "2025-03-27",
        "likes" => 18,
        "comments" => 1,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/limonadas.jpg",
        "photos" => ["images/limonadas.jpg"],
        "meal" => "Užkandžiai",
        "type" => "Gėrimai",
        "diet" => "Vaikams",
        "cuisine" => "Lietuvių"
    ],
    [
        "title" => "Makaronai kinietiškai",
        "desc" => "Apkepti makaronai su daržovėmis ir sojos padažu.",
        "portions" => 2,
        "time" => "25 min.",
        "author" => "Lina",
        "date" => "2025-03-26",
        "likes" => 12,
        "comments" => 2,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/makaronai_kinietiskai.jpg",
        "photos" => ["images/makaronai_kinietiskai.jpg"],
        "meal" => "Vakarienė",
        "type" => "Pagrindiniai patiekalai",
        "diet" => "Veganiški patiekalai",
        "cuisine" => "Kiniečių"
    ],
    [
        "title" => "Takos su jautiena",
        "desc" => "Traškūs takos su malta jautiena, daržovėmis ir sūriu.",
        "portions" => 8,
        "time" => "30 min.",
        "author" => "Liepa",
        "date" => "2025-03-25",
        "likes" => 24,
        "comments" => 4,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/takos.jpg",
        "photos" => ["images/takos.jpg"],
        "meal" => "Vakarienė",
        "type" => "Pagrindiniai patiekalai",
        "diet" => "Be glitimo",
        "cuisine" => "Meksikiečių"
    ],
    [
        "title" => "Tiramisu",
        "desc" => "Itališkas desertas su kava ir maskarponės kremu.",
        "portions" => 4,
        "time" => "20 min.",
        "author" => "Beatričė",
        "date" => "2025-03-24",
        "likes" => 35,
        "comments" => 5,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/tiramisu.webp",
        "photos" => ["images/tiramisu.webp"],
        "meal" => "Desertai",
        "type" => "Desertai",
        "diet" => "Vegetariški patiekalai",
        "cuisine" => "Italų"
    ],
    [
        "title" => "Makaronų salotos su kepta vištiena",
        "desc" => "Sočios salotos su makaronais, vištiena ir daržovėmis.",
        "portions" => 3,
        "time" => "25 min.",
        "author" => "Viktorija",
        "date" => "2025-03-23",
        "likes" => 16,
        "comments" => 1,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/Makaronu-salotos-su-kepta-vistiena.jpg",
        "photos" => ["images/Makaronu-salotos-su-kepta-vistiena.jpg"],
        "meal" => "Pietūs",
        "type" => "Salotos",
        "diet" => "Vaikams",
        "cuisine" => "Lietuvių"
    ],
    [
        "title" => "Meksikietiška sriuba",
        "desc" => "Aštri pomidorinė sriuba su kukurūzais ir prieskoniais.",
        "portions" => 4,
        "time" => "35 min.",
        "author" => "Karolis",
        "date" => "2025-03-22",
        "likes" => 20,
        "comments" => 3,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/meksikietiska_sriuba.jpg",
        "photos" => ["images/meksikietiska_sriuba.jpg"],
        "meal" => "Vakarienė",
        "type" => "Sriubos",
        "diet" => "Be glitimo",
        "cuisine" => "Meksikiečių"
    ],
    [
        "title" => "Mini burgeriai",
        "desc" => "Mini mėsainių rinkinys vakarėliams ar užkandžiams.",
        "portions" => 16,
        "time" => "20 min.",
        "author" => "Emilija",
        "date" => "2025-03-21",
        "likes" => 27,
        "comments" => 3,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/mini_burgeriai.jpg",
        "photos" => ["images/mini_burgeriai.jpg"],
        "meal" => "Užkandžiai",
        "type" => "Užkandžiai",
        "diet" => "Vaikams",
        "cuisine" => "Amerikiečių"
    ],
    [
        "title" => "Naminiai suši",
        "desc" => "Lengvai paruošiami suši su lašiša ir daržovėmis.",
        "portions" => 4,
        "time" => "30 min.",
        "author" => "Nerijus",
        "date" => "2025-03-20",
        "likes" => 14,
        "comments" => 2,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/naminiai_sushi.jpg",
        "photos" => ["images/naminiai_sushi.jpg"],
        "meal" => "Vakarienė",
        "type" => "Pagrindiniai patiekalai",
        "diet" => "Vegetariški patiekalai",
        "cuisine" => "Japonų"
    ],
    [
        "title" => "Naminiai varškės sūreliai",
        "desc" => "Skanūs ir sveikesni varškės sūreliai aplieti šokoladu.",
        "portions" => 6,
        "time" => "25 min.",
        "author" => "Agnė",
        "date" => "2025-03-19",
        "likes" => 33,
        "comments" => 1,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/naminiai-varskes-sureliai-receptas.jpg",
        "photos" => ["images/naminiai-varskes-sureliai-receptas.jpg"],
        "meal" => "Desertai",
        "type" => "Desertai",
        "diet" => "Be glitimo",
        "cuisine" => "Lietuvių"
    ],
    [
        "title" => "Ramen sriuba",
        "desc" => "Tradicinė japoniška sriuba su makaronais ir daržovėmis.",
        "portions" => 2,
        "time" => "35 min.",
        "author" => "Haris",
        "date" => "2025-03-18",
        "likes" => 16,
        "comments" => 2,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/ramenas.jpg",
        "photos" => ["images/ramenes.jpg"],
        "meal" => "Vakarienė",
        "type" => "Sriubos",
        "diet" => "Veganiški patiekalai",
        "cuisine" => "Japonų"
    ],
    [
        "title" => "Ryžių dubenėlis su lašiša",
        "desc" => "Sveikas ir sotus ryžių bowlas su avokadu ir daržovėmis.",
        "portions" => 1,
        "time" => "20 min.",
        "author" => "Karolina",
        "date" => "2025-03-17",
        "likes" => 22,
        "comments" => 0,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/ryziu_bowlas.jpg",
        "photos" => ["images/ryziu_bowlas.jpg"],
        "meal" => "Pietūs",
        "type" => "Pagrindiniai patiekalai",
        "diet" => "Sveika mityba",
        "cuisine" => "Japonų"
    ],
    [
        "title" => "Braškių ir bananų glotnutis",
        "desc" => "Švelnus vaisių kokteilis su chia sėklomis pusryčiams.",
        "portions" => 1,
        "time" => "7 min.",
        "author" => "Goda",
        "date" => "2025-03-16",
        "likes" => 18,
        "comments" => 0,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/smoothie.jpg",
        "photos" => ["images/smoothie.jpg"],
        "meal" => "Pusryčiai",
        "type" => "Gėrimai",
        "diet" => "Vegetariški patiekalai",
        "cuisine" => "Amerikiečių"
    ],
    [
        "title" => "Užkandukai su lašiša",
        "desc" => "Traškūs užkandžiai su kreminiu sūriu ir rūkyta lašiša.",
        "portions" => 4,
        "time" => "15 min.",
        "author" => "Lukrecija",
        "date" => "2025-03-15",
        "likes" => 21,
        "comments" => 1,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/uzkandis.jpg",
        "photos" => ["images/uzkandis.jpg"],
        "meal" => "Užkandžiai",
        "type" => "Užkandžiai",
        "diet" => "Sveika mityba",
        "cuisine" => "Italų"
    ],
    [
        "title" => "Vegetariškas pusryčių dubenėlis",
        "desc" => "Subalansuoti pusryčiai su kiaušiniu ir daržovėmis.",
        "portions" => 1,
        "time" => "12 min.",
        "author" => "Lėja",
        "date" => "2025-03-14",
        "likes" => 20,
        "comments" => 1,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/vegetariski_pusryciai.jpg",
        "photos" => ["images/vegetariski_pusryciai.jpg"],
        "meal" => "Pusryčiai",
        "type" => "Salotos",
        "diet" => "Vegetariški patiekalai",
        "cuisine" => "Kiniečių"
    ],
    [
        "title" => "Kinietiškai apkepta vištiena",
        "desc" => "Traški vištiena saldžiarūgščiame padaže.",
        "portions" => 4,
        "time" => "30 min.",
        "author" => "Ignas",
        "date" => "2025-03-13",
        "likes" => 23,
        "comments" => 2,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/vistiena_kinietiskai.jpg",
        "photos" => ["images/vistiena_kinietiskai.jpg"],
        "meal" => "Pietūs",
        "type" => "Pagrindiniai patiekalai",
        "diet" => "Be glitimo",
        "cuisine" => "Kiniečių"
    ],
    [
        "title" => "Salotos su lašiša",
        "desc" => "Gaivios ir maistingos salotos su lašiša.",
        "portions" => 2,
        "time" => "18 min.",
        "author" => "Aida",
        "date" => "2025-03-12",
        "likes" => 29,
        "comments" => 2,
        "tips" => "",
        "ingredients" => [],
        "instructions" => [],
        "img" => "images/sveikas maistas.jpeg",
        "photos" => ["images/sveikas maistas.jpeg"],
        "meal" => "Pietūs",
        "type" => "Pagrindiniai patiekalai",
        "diet" => "Vegetariški patiekalai",
        "cuisine" => "Japonų"
    ]    
    
];

// // Receptų įkėlimas
// foreach ($recipes as $recipe) {
//     $title = $conn->real_escape_string($recipe['title']);
//     $description = $conn->real_escape_string($recipe['desc'] ?? '');
//     $portions = $recipe['portions'] ?? 1;
//     $time = $conn->real_escape_string($recipe['time'] ?? '');
    
//     // Tik naudotojai, kurie egzistuoja: ID nuo 2 iki 6
//     $author_id = rand(2, 6);

//     // Data iš recepto, bet validi (jei kas) – arba šiandien
//     $created_at = $recipe['date'] ?? date("Y-m-d");

//     $tips = $conn->real_escape_string($recipe['tips'] ?? '');
//     $meal = $conn->real_escape_string($recipe['meal'] ?? '');
//     $type = $conn->real_escape_string($recipe['type'] ?? '');
//     $diet = $conn->real_escape_string($recipe['diet'] ?? '');
//     $cuisine = $conn->real_escape_string($recipe['cuisine'] ?? '');
//     $img = $conn->real_escape_string($recipe['img'] ?? '');
//     $photos = json_encode($recipe['photos'] ?? [], JSON_UNESCAPED_UNICODE);
//     $likes = $recipe['likes'] ?? 0;
//     $comments = $recipe['comments'] ?? 0;

//     $instructions = json_encode($recipe['instructions'] ?? [], JSON_UNESCAPED_UNICODE);
//     $ingredients = json_encode($recipe['ingredients'] ?? [], JSON_UNESCAPED_UNICODE);

//     $sql = "INSERT INTO recipes 
//         (title, description, instructions, portions, time, author_id, created_at, tips, meal, type, diet, cuisine, img, photos, likes, comments)
//         VALUES (
//             '$title', '$description', '$instructions', $portions, '$time', $author_id, '$created_at', '$tips', 
//             '$meal', '$type', '$diet', '$cuisine', '$img', '$photos', $likes, $comments
//         )";

//     if ($conn->query($sql) === TRUE) {
//         echo " Receptas <strong>'$title'</strong> sėkmingai įkeltas.<br>";
//     } else {
//         echo " Klaida įkeliant <strong>'$title'</strong>: " . $conn->error . "<br>";
//     }
// }

$conn->close();
exit;